sonar.projectKey=testing0001
sonar.projectName=testing0001
sonar.projectVersion=1.0
sonar.sources=src
sonar.inclusions=src/sonarTraining.js
sonar.exclusions=dist/**,node_modules/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_ebd094800ec77af66ec94fe886a52e3cc1df7f05